import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

function slugify(text) {
  return text.toString().toLowerCase().trim()
    .replace(/[^a-z0-9]+/g, '-').replace(/^[-]+/g, '').replace(/[-]+$/g, '');
}

const newProducts = [
  { name:'Blue Lace Agate Bracelet', category:'Bracelets', price:1600, original_price:2000, stamp:'Fresh', description:'Calming sky-blue banded agate beads designed to soothe an overactive mind and open smooth pathways of communication.', philosophy:'Soft speech carries deep truth. Speak from tranquility.', details:'8mm natural Blue Lace Agate beads. Durable stretch cord.', origin:'Namibia', chakra:'Throat', effect:'Enhances peaceful communication and reduces stress.', usage:'Wear on non-dominant wrist for emotional tranquility.', image_url:'/assets/images/Blue Lasagate Bracelet/Blue Lace Agate Bracelet 1 original.webp', gallery_images:['/assets/images/Blue Lasagate Bracelet/Blue Lace Agate Bracelet 2 original.webp','/assets/images/Blue Lasagate Bracelet/Blue Lace Agate Bracelet 3 original.webp'] },
  { name:'Carnelian Bracelet', category:'Bracelets', price:1500, original_price:1900, stamp:'Hot', description:'Vibrant fiery orange carnelian beads to awaken motivation, vital creativity, and bold action.', philosophy:'Action burns through hesitation. Ignite your momentum.', details:'8mm polished carnelian beads with rich red-orange hues.', origin:'Madagascar', chakra:'Sacral', effect:'Boosts energy, motivation, and physical vitality.', usage:'Wear on dominant wrist when taking bold steps.', image_url:'/assets/images/Carnelian Bracelet/Carnelian Bracelet 1 original.webp', gallery_images:['/assets/images/Carnelian Bracelet/Carnelian Bracelet 2 original.webp','/assets/images/Carnelian Bracelet/Carnelian Bracelet 3 original.webp'] },
  { name:'Carnelian Crystal Tree', category:'Utility & Decor', price:3200, original_price:3800, stamp:'Fresh', description:'A handcrafted wire gem tree featuring glowing carnelian leaves to energize creative spaces.', philosophy:'A space infused with fire attracts abundant creation.', details:'Handcrafted copper wire structure on a natural quartz cluster base. ~15cm tall.', origin:'India', chakra:'Sacral', effect:'Fills room with active, vibrant, creative frequency.', usage:'Place on your work desk or studio space for continuous inspiration.', image_url:'/assets/images/Carnelian Crystal Tree/Carnelian Crystal Tree 1 original.webp', gallery_images:['/assets/images/Carnelian Crystal Tree/Carnelian Crystal Tree 2 original.webp','/assets/images/Carnelian Crystal Tree/Carnelian Crystal Tree 3 original.webp'] },
  { name:'Clear Quartz Crystal Pyramid', category:'Utility & Decor', price:2900, original_price:3400, stamp:null, description:'A sacred geometry pyramid carved from high-transparency Clear Quartz, amplifying focus and intention in any chamber.', philosophy:'The pyramid focuses intention to a single sharp apex.', details:'50mm base width, hand-cut clear quartz pyramid.', origin:'Brazil', chakra:'Crown', effect:'Focuses and amplifies energetic vibrations in a space.', usage:'Position centrally in meditation areas or atop written intentions.', image_url:'/assets/images/Clear Quartz Crystal Pyramid/Clear Quartz Crystal Pyramid 1 original.webp', gallery_images:['/assets/images/Clear Quartz Crystal Pyramid/Clear Quartz Crystal Pyramid 2 original.webp','/assets/images/Clear Quartz Crystal Pyramid/Clear Quartz Crystal Pyramid 3 original.webp'] },
  { name:'Clear Quartz Bracelet', category:'Bracelets', price:1400, original_price:1800, stamp:null, description:'Pure clear quartz beads that act as a master healer and personal intention amplifier.', philosophy:'Clarity is the canvas of true direction.', details:'8mm high-grade clear quartz beads on elastic cord.', origin:'Brazil', chakra:'Crown', effect:'Amplifies personal energy field and enhances mental clarity.', usage:'Pair with any other crystal bracelet to amplify its properties.', image_url:'/assets/images/Clear Quartz Bracelet/Clear Quartz Bracelet 1 original.webp', gallery_images:['/assets/images/Clear Quartz Bracelet/Clear Quartz Bracelet 2 original.webp','/assets/images/Clear Quartz Bracelet/Clear Quartz Bracelet 3 original.webp'] },
  { name:'Golden Hematite Bracelet', category:'Bracelets', price:1800, original_price:2200, stamp:'Popular', description:'Lustrous golden hematite beads fusing protective grounding with solar confidence.', philosophy:'Walk with golden roots. Your foundation shines outward.', details:'8mm golden-coated natural hematite beads.', origin:'Brazil', chakra:'Root', effect:'Grounds while boosting self-confidence and willpower.', usage:'Wear daily for a blend of grounding stability and personal radiance.', image_url:'/assets/images/Golden Hamatite Bracelet/Golden Hematite Bracelet 1 original.webp', gallery_images:['/assets/images/Golden Hamatite Bracelet/Golden Hematite Bracelet 2 original.webp','/assets/images/Golden Hamatite Bracelet/Golden Hematite Bracelet 3 original.webp'] },
  { name:'Green Aventurine Crystal Pyramid', category:'Utility & Decor', price:2800, original_price:3300, stamp:null, description:'A hand-cut Green Aventurine pyramid channeling focused luck, growth, and opportunity energy.', philosophy:'Luck is energy focused through intention.', details:'50mm base Green Aventurine pyramid with natural shimmer.', origin:'India', chakra:'Heart', effect:'Radiates opportunity, growth, and heart-centred prosperity.', usage:'Position in workspace for career luck and abundance flow.', image_url:'/assets/images/Green Aventurine Crystal Pyramid/Green Aventurine Crystal Pyramid 1 original.webp', gallery_images:['/assets/images/Green Aventurine Crystal Pyramid/Green Aventurine Crystal Pyramid 2 original.webp','/assets/images/Green Aventurine Crystal Pyramid/Green Aventurine Crystal Pyramid 3 original.webp'] },
  { name:'Green Aventurine Crystal Tree', category:'Utility & Decor', price:3500, original_price:4000, stamp:'Fresh', description:'A handmade gem tree with lush green aventurine leaves to attract luck, growth, and prosperity.', philosophy:'Growth is quiet and constant. Position yourself in its flow.', details:'Hand-wired copper tree with aventurine chip leaves on quartz base. ~16cm tall.', origin:'India', chakra:'Heart', effect:'Attracts luck, prosperity, and emotional growth.', usage:'Place near entrance or financial workspace for sustained abundance.', image_url:'/assets/images/Green Aventurine Crystal Tree/Green Aventurine Crystal Tree 1 original.webp', gallery_images:['/assets/images/Green Aventurine Crystal Tree/Green Aventurine Crystal Tree 2 original.webp','/assets/images/Green Aventurine Crystal Tree/Green Aventurine Crystal Tree 3 original.webp'] },
  { name:'Green Jade Bracelet', category:'Bracelets', price:1900, original_price:2400, stamp:'Popular', description:'Deep green jade beads revered for centuries as the stone of harmony, luck, and eternal balance.', philosophy:'True wealth is inner harmony expressed outward.', details:'8mm Grade-A nephrite jade beads. Smooth polish.', origin:'Myanmar', chakra:'Heart', effect:'Promotes harmony, luck, and emotional equilibrium.', usage:'Wear during negotiation, decision-making, or life transitions.', image_url:'/assets/images/Green Jade Bracelet/Green Jade Bracelet 1 original.webp', gallery_images:['/assets/images/Green Jade Bracelet/Green Jade Bracelet 2 original.webp','/assets/images/Green Jade Bracelet/Green Jade Bracelet 3 original.webp'] },
  { name:'Pink Tourmaline Bracelet', category:'Bracelets', price:2200, original_price:2800, stamp:'Rare', description:'Ethereal pink tourmaline beads radiating unconditional love, emotional healing, and compassion.', philosophy:'Vulnerability is the highest form of energetic power.', details:'8mm natural pink tourmaline beads with visible crystalline structure.', origin:'Brazil', chakra:'Heart', effect:'Opens the heart to deep self-love and emotional repair.', usage:'Wear during emotional processing or relationship healing phases.', image_url:'/assets/images/Pink Tourmaline Bracelet/Pink Tourmaline Bracelet 1 original.webp', gallery_images:['/assets/images/Pink Tourmaline Bracelet/Pink Tourmaline Bracelet 2 original.webp','/assets/images/Pink Tourmaline Bracelet/Pink Tourmaline Bracelet 3 original.webp'] },
  { name:'Pyrite Bracelet', category:'Bracelets', price:1700, original_price:2100, stamp:'Hot', description:'Brilliant metallic pyrite beads forming a shield of abundance and energetic protection.', philosophy:"Fool's gold is for the wise. True wealth starts within.", details:'8mm polished pyrite beads with high mirror sheen.', origin:'Peru', chakra:'Solar Plexus', effect:'Shields against negative energy while attracting wealth.', usage:'Wear on dominant hand during business or financial activities.', image_url:'/assets/images/Pyrite Bracelet/Pyrite Bracelet 1 original.webp', gallery_images:['/assets/images/Pyrite Bracelet/Pyrite Bracelet 2 original.webp','/assets/images/Pyrite Bracelet/Pyrite Bracelet 3 original.webp'] },
  { name:'Pyrite Crystal Pyramid', category:'Utility & Decor', price:3200, original_price:3800, stamp:null, description:'A densely metallic pyrite pyramid combining sacred geometry with wealth-shielding frequencies.', philosophy:'Protect what you build. Attract what you deserve.', details:'50mm base pyrite pyramid, hand-polished.', origin:'Peru', chakra:'Solar Plexus', effect:'Acts as a magnetic wealth generator and energetic barrier.', usage:'Place near financial documents, cash registers, or desk.', image_url:'/assets/images/Pyrite Crystal Pyramid/Pyrite Crystal Pyramid 1 original.webp', gallery_images:['/assets/images/Pyrite Crystal Pyramid/Pyrite Crystal Pyramid 2 original.webp','/assets/images/Pyrite Crystal Pyramid/Pyrite Crystal Pyramid 3 original.webp'] },
  { name:'Pyrite Crystal Tree', category:'Utility & Decor', price:3800, original_price:4400, stamp:'Fresh', description:'An extraordinary wire gem tree laden with sparkling pyrite leaves to manifest prosperity.', philosophy:'Roots in discipline, branches reaching for wealth.', details:'Hand-crafted copper wire tree with pyrite nuggets. Height ~16cm.', origin:'India', chakra:'Solar Plexus', effect:'Radiates wealth and strong energetic defense.', usage:'Place in central foyer or executive desk area.', image_url:'/assets/images/Pyrite Crystal Tree/Pyrite Crystal Tree 1 original.webp', gallery_images:['/assets/images/Pyrite Crystal Tree/Pyrite Crystal Tree 2 original.webp','/assets/images/Pyrite Crystal Tree/Pyrite Crystal Tree 3 original.webp'] },
  { name:'Red Jasper Bracelet', category:'Bracelets', price:1300, original_price:1700, stamp:null, description:'Deep brick-red jasper beads providing steady endurance, root chakra stability, and physical stamina.', philosophy:'Patience and presence weather any storm.', details:'8mm smooth opaque red jasper beads.', origin:'South Africa', chakra:'Root', effect:'Provides physical endurance and deep grounding energy.', usage:'Wear during intense physical activity or stressful projects.', image_url:'/assets/images/Red Jasper Bracelet/Red Jasper Bracelet 1 original.webp', gallery_images:['/assets/images/Red Jasper Bracelet/Red Jasper Bracelet 2 original.webp','/assets/images/Red Jasper Bracelet/Red Jasper Bracelet 3 original.webp'] },
  { name:'Rutile Quartz Bracelet', category:'Bracelets', price:2600, original_price:3200, stamp:'Rare', description:'Clear quartz beads infused with golden needles of rutile, accelerating spiritual evolution and mental focus.', philosophy:'Divine threads illuminate the path forward.', details:'8mm high-grade golden rutile quartz beads.', origin:'Brazil', chakra:'Crown', effect:'Accelerates manifestation and clears spiritual blockages.', usage:'Wear during intention-setting or meditation practice.', image_url:'/assets/images/Rutile Quartz Bracelet/Rutile Quartz Bracelet 1 original.webp', gallery_images:['/assets/images/Rutile Quartz Bracelet/Rutile Quartz Bracelet 2 original.webp','/assets/images/Rutile Quartz Bracelet/Rutile Quartz Bracelet 3 original.webp'] },
  { name:'Selenite Bracelet', category:'Bracelets', price:1500, original_price:1900, stamp:'Fresh', description:'Silky white selenite beads providing continuous aura purification and mental stillness throughout your day.', philosophy:'Pure light clears all residual shadow.', details:'8mm natural translucent white selenite beads.', origin:'Morocco', chakra:'Crown', effect:'Cleanses personal energy field and enhances higher awareness.', usage:'Wear daily. Avoid soaking in water to preserve selenite lustre.', image_url:'/assets/images/Selenite Bracelet/Selenite Bracelet 1 original.webp', gallery_images:['/assets/images/Selenite Bracelet/Selenite Bracelet 2 original.webp','/assets/images/Selenite Bracelet/Selenite Bracelet 3 original.webp'] },
  { name:'Sodalite Bracelet', category:'Bracelets', price:1400, original_price:1800, stamp:null, description:'Deep royal blue sodalite beads with white vein inclusions, fostering rational thought, truth, and intuitive insight.', philosophy:'Combine logic with intuition for untangling complexity.', details:'8mm smooth sodalite beads.', origin:'Brazil', chakra:'Third Eye', effect:'Promotes mental clarity, logic, and emotional balance.', usage:'Wear during deep study, writing, or analytical endeavors.', image_url:'/assets/images/Sodalite Bracelet/Sodalite Bracelet 1 original.webp', gallery_images:['/assets/images/Sodalite Bracelet/Sodalite Bracelet 2 original.webp','/assets/images/Sodalite Bracelet/Sodalite Bracelet 3 original.webp'] },
  { name:'Turquoise Bracelet', category:'Bracelets', price:2100, original_price:2600, stamp:'Popular', description:'Vibrant robin-egg turquoise beads sacred to ancient traditions for protection, wisdom, and truth.', philosophy:'Your authentic voice is your sacred protection.', details:'8mm genuine natural turquoise beads.', origin:'Arizona, USA', chakra:'Throat', effect:'Protects the traveler and inspires honest expression.', usage:'Wear daily as a protective stone for voice and personal aura.', image_url:'/assets/images/Turquoise Bracelet/Turquoise Bracelet 1 original.webp', gallery_images:['/assets/images/Turquoise Bracelet/Turquoise Bracelet 2 original.webp','/assets/images/Turquoise Bracelet/Turquoise Bracelet 3 original.webp'] },
];

async function seed() {
  let success = 0;
  let fail = 0;
  for (const p of newProducts) {
    const slug = slugify(p.name);
    // Check if already exists
    const { data: existing } = await supabase.from('products').select('id').eq('slug', slug).maybeSingle();
    if (existing) {
      console.log(`SKIP (exists): ${p.name}`);
      success++;
      continue;
    }
    const row = {
      slug,
      name: p.name,
      category: p.category,
      price: p.price,
      original_price: p.original_price,
      stamp: p.stamp || 'none',
      description: p.description,
      philosophy: p.philosophy,
      details: p.details,
      origin: p.origin,
      chakra: p.chakra,
      effect: p.effect,
      usage: p.usage,
      image_url: p.image_url,
      gallery_images: p.gallery_images,
      stock: 10,
      active: true,
      featured: false,

    };
    const { error } = await supabase.from('products').insert(row);
    if (error) {
      console.error(`FAIL: ${p.name} — ${error.message}`);
      fail++;
    } else {
      console.log(`OK: ${p.name}`);
      success++;
    }
  }
  console.log(`\nDone. Success: ${success}, Failed: ${fail}`);
}

seed().catch(err => { console.error(err); process.exit(1); });
