-- Run this in Supabase Dashboard > SQL Editor after creating the table

INSERT INTO public.limited_products (
  collection, name, subtitle, slug, short_description, long_story,
  crystal_constituents, charm, feeling, reason_to_gift, crystal_charm_qualities,
  care_instructions, whats_included, gifting_note,
  seo_description, meta_title, meta_description,
  price, stock, active
) VALUES 
(
  'Rakhi''26', 
  'Nazar', 
  'The Rakhi of Protection', 
  'rakhi-26-nazar', 
  'For the sibling whose strength deserves quiet protection.', 
  'A bond of protection doesn''t always need to be loud; sometimes it is a silent promise to stand as a shield. The Nazar Rakhi is crafted for the sibling who is your anchor. It weaves together the absorbing depth of Black Tourmaline with the timeless vigilance of the Evil Eye, creating a talisman that guards their energy and honors your enduring care.',
  'Black Tourmaline', 
  'Evil Eye', 
  'Protection • Strength • Peace', 
  'For the sibling you always want protected, grounded and surrounded by positive energy.', 
  'Black Tourmaline helps absorb unwanted negativity while the Evil Eye symbolizes protection from negative intentions.',
  'Keep away from water, perfumes, and harsh chemicals. Gently wipe with a soft cloth to maintain its luster.', 
  'One handcrafted Nazar Rakhi, a keepsake envelope, and a meaning card detailing the crystal''s properties.', 
  'May this thread be a quiet guardian, reflecting the protective love we share.',
  'The Nazar Rakhi by The Sacred Store features Black Tourmaline and an Evil Eye charm for protection. A premium spiritual gift for Raksha Bandhan.', 
  'Nazar Rakhi - Protection & Strength | The Sacred Store', 
  'Gift the Nazar Rakhi, featuring Black Tourmaline and an Evil Eye charm. A premium handcrafted rakhi for protection and peace.',
  499, 50, true
),
(
  'Rakhi''26', 
  'Saanjh', 
  'The Rakhi of Affection', 
  'rakhi-26-saanjh', 
  'For the moments that keep two hearts connected, no matter the distance.', 
  'Like the soft glow of dusk settling over a cherished memory, the Saanjh Rakhi embodies the gentle warmth of siblinghood. Merging the tender affection of Rose Quartz with the grounding shield of Black Tourmaline and an Evil Eye, it is designed to hold your love close while ensuring emotional safety through every season of life.',
  'Rose Quartz, Black Tourmaline', 
  'Evil Eye', 
  'Affection • Care • Emotional Safety', 
  'For expressing unconditional love while wishing protection and emotional harmony.', 
  'Rose Quartz symbolizes compassion and affection, while Black Tourmaline and the Evil Eye represent grounding and protection.',
  'Keep away from moisture and direct sunlight for prolonged periods. Store in the provided keepsake envelope.', 
  'One handcrafted Saanjh Rakhi, a keepsake envelope, and a meaning card detailing the crystal''s properties.', 
  'A symbol of my affection, wishing you emotional harmony and steadfast protection.',
  'The Saanjh Rakhi by The Sacred Store features Rose Quartz, Black Tourmaline, and an Evil Eye charm. A premium emotional gifting rakhi.', 
  'Saanjh Rakhi - Affection & Care | The Sacred Store', 
  'Gift the Saanjh Rakhi, featuring Rose Quartz and Black Tourmaline. A handcrafted premium rakhi wishing affection, care, and emotional safety.',
  499, 50, true
),
(
  'Rakhi''26', 
  'Ananta', 
  'The Rakhi of Forever', 
  'rakhi-26-ananta', 
  'A reminder that some bonds never need words to remain unbroken.', 
  'Some connections transcend time and distance, remaining as clear and constant as a quiet dawn. The Ananta Rakhi is an homage to this eternal bond. Featuring the illuminating clarity of Clear Quartz intertwined with the soft devotion of Rose Quartz and sealed with an Infinity Loop, it stands as a beautiful testament to a lifelong connection built on absolute trust.',
  'Rose Quartz, Clear Quartz', 
  'Infinity Loop', 
  'Forever • Trust • Connection', 
  'To celebrate an enduring sibling bond and lifelong connection.', 
  'Rose Quartz represents warmth and love, Clear Quartz symbolizes clarity, and the Infinity Loop represents an unending bond.',
  'Handle with care. Avoid contact with perfumes or lotions to protect the crystal''s natural finish.', 
  'One handcrafted Ananta Rakhi, a keepsake envelope, and a meaning card detailing the crystal''s properties.', 
  'Here is to a bond that stretches infinitely, grounded in clarity and love.',
  'The Ananta Rakhi by The Sacred Store features Rose Quartz, Clear Quartz, and an Infinity Loop charm. A premium handcrafted rakhi for enduring bonds.', 
  'Ananta Rakhi - Forever & Trust | The Sacred Store', 
  'Gift the Ananta Rakhi, featuring Rose Quartz and Clear Quartz with an Infinity Loop charm. Celebrate a lifelong sibling connection with this premium design.',
  499, 50, true
),
(
  'Rakhi''26', 
  'Vriddhi', 
  'The Rakhi of Growth', 
  'rakhi-26-vriddhi', 
  'A wish for every new beginning to bring confidence, opportunity, and joy.', 
  'Growth is a beautiful journey best walked with those who believe in you the most. The Vriddhi Rakhi is crafted to be a beacon of abundance and unyielding support. With the optimistic, opportunity-drawing essence of Green Aventurine paired alongside nurturing Rose Quartz and the Infinity Loop, it serves as a powerful wish for continuous, joyful growth.',
  'Rose Quartz, Green Aventurine', 
  'Infinity Loop', 
  'Growth • Prosperity • Support', 
  'For wishing your sibling continued growth, confidence and abundance.', 
  'Green Aventurine symbolizes opportunity and growth, Rose Quartz represents care, and the Infinity Loop signifies a lasting relationship.',
  'Store carefully in a dry place. Clean gently with a dry, soft cloth.', 
  'One handcrafted Vriddhi Rakhi, a keepsake envelope, and a meaning card detailing the crystal''s properties.', 
  'May your path always be paved with opportunity, growth, and my unwavering support.',
  'The Vriddhi Rakhi by The Sacred Store features Green Aventurine, Rose Quartz, and an Infinity Loop. A premium spiritual rakhi for growth and prosperity.', 
  'Vriddhi Rakhi - Growth & Prosperity | The Sacred Store', 
  'Gift the Vriddhi Rakhi, an elegant design of Green Aventurine and Rose Quartz with an Infinity Loop, wishing growth and prosperity.',
  499, 50, true
);
